language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
